Create Popup Modal
Ol-create/Mobile-Project2.0 pull request #14
Opened 2022-03-12 13:16 UTC by Ol-create

- Create a data object.
- Create project array
- Dynamically render modal box with javascript function
- Create project title node
- Create language list node
- Create an Image node
- Create page description text node
- Add event listener to close modal
- Append modal to the body element
- Add event listener to show popup window

2022-03-12 14:39 UTC, brytebee requested changes
Hi Team 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- Excellent PR summary✔️
- Good commit messages✔️
- no linter errors✔️
- clean code✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-12 14:39 UTC, brytebee commented on dom.js
> +
- [ ] **Optional:** You have done a really good job so far. I suggest, however, that when the popup window is open, the main page should not scroll behind the popup.

- [ ] **Required:** On the desktop popup, kindly make the following changes to follow the design template:

Your Design | Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/158021929-9660b4ba-1724-4911-9e68-1de8faf0e8b9.png) | ![image](https://user-images.githubusercontent.com/27709832/158022008-c4db3e3b-0347-47e3-9d43-38f5c609aeec.png)

- 1 and 2: The padding should be adjusted.
- 3 and 4: Position appropriately the button and text.
- 5 and 6: Center the modal popup on the browser window.

- [ ] **Required:** On the button, fix the font family to follow the design.

2022-03-12 18:37 UTC, medaminedev66 requested changes
Hi @Ol-create , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-12 18:37 UTC, medaminedev66 commented on dom.js
> +  const divPrj = document.createElement('div');
- [ ] You have built a great pop-up design. Let's make it better by fixing the height of your pop-up so your pop-up design is complete.
- Your design:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/77190203/158030023-676cd4a7-546a-410f-96c2-38e5e5df8f23.png">

2022-03-12 18:37 UTC, medaminedev66 commented on dom.js
> +  });
- [ ] In the mobile version, there is an overlap between languages and the project's image. Kindly fix this to improve your UI design.
- Your design:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/77190203/158030123-f05134f2-4d60-4b73-b83b-e52617f771de.png">

This module is about HTML & CSS, and the Figma template is very detailed. Sticking to the design will help you practice your HTML & CSS skills better.

2022-03-12 20:34 UTC, Davidosky007 reviewed
Hello @Ol-create  👋,

_This is an additional review as a result of the second opinion request._
Well done implementing the popup section for both mobile and desktop 👍  but you missed the languages part for the mobile view kindly fix this and submit it for another review 
![image](https://user-images.githubusercontent.com/52497246/158034059-802854c6-d774-4aad-b1ee-769393412b04.png)


As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀! //

2022-03-12 21:50 UTC, BenMukebo approved these changes
Hi @Ol-create , 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media4.giphy.com/media/W2b8JkhIwnVH7Sr1zl/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-24 15:22 UTC, Ol-create commented on dom.js
> +
Thank you very much @brytebee issue resolved :heavy_check_mark:

2023-04-24 15:24 UTC, Ol-create commented on dom.js
> +  });
Thank you for your time and effort @medaminedev66 :heavy_check_mark: 
I appreciate you :+1:

2023-04-24 16:11 UTC, closed without merging