Portfolio Desktop version
Ol-create/Mobile-Project2.0 pull request #4
Opened 2022-02-26 18:16 UTC by Ol-create

- Add styles to the welcome section
- Add background image to welcome section
- Add menu to the navbar
- Add styles to recent work and contact form section

2022-02-26 19:18 UTC, MrBrN197 requested changes
## Hi, @Ol-create  👋  

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 19:18 UTC, MrBrN197 commented on index.html
>                          Language</li>
- [ ] In this section, I'd like you to notice that the text for the headings of "Language", "Framework", "Skills" need to be much bigger than the text below them.
- [ ] the text in each of these `li`s should also be left-aligned according to the Figma reference.
- [ ] And if you notice carefully there is some space between the heading of the section for example "Language" and the `li`s (Ruby, Html, CSS) text. 
The size of the heading text and spacing between the heading text and the `li`s is very important for readability it should be obvious to a user that the "Language" text is actually a heading and the `li`s text are actually examples of the heading. the orange icon helps in that regard but the spacing and `font-size` difference would really help take a look at the Figma design. 

image


Your Design | Reference Design
-|-
![image](https://user-images.githubusercontent.com/18730106/155856001-289b43e4-a4c7-4717-903a-959d96f0117e.png)|![image](https://user-images.githubusercontent.com/18730106/155856009-c3574f6a-0641-4667-9ec2-39ba9eaa4482.png)

2022-02-26 19:18 UTC, MrBrN197 commented on index.html
> +        </section>
- [ ] The background color on this footer section is not matching the Figma. the Figma reference has a pure white background. Please make this change in order to match the reference as best you can.
- [ ] You also have a pinkish background on your `textarea`. this is not in accordance with the Figma design and if you could also make this small change, it would be appreciated.
- [ ] Notice the text on the left is also left aligned. a simple addition of `text-align: center` should fix this easily.

2022-02-27 00:15 UTC, merged

2022-02-27 00:16 UTC, Ol-create commented
- Add desktop version